apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cheetah-nodejs 
  janus-idp.io/tekton: cheetah-nodejs
  backstage.io/kubernetes-id: cheetah-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cheetah-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  