apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cheetah-nodejs
  janus-idp.io/tekton: cheetah-nodejs
  backstage.io/kubernetes-id: cheetah-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cheetah-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
